export const listOfNis = [
  "School of Physics and Mathematics in Nur-Sultan",
  "Nazarbayev Intellectual School of Nur-Sultan",
  "School of Physics and Mathematics in Kokshetau",
  "School of Physics and Mathematics in Taldykorgan",
  "School of Physics and Mathematics in Semey",
  "School of Physics and Mathematics in Uralsk",
  "School of Chemistry and Biology in Ust-Kamenogorsk",
  "School of Physics and Mathematics in Aktobe",
  "School of Chemistry and Biology in Karaganda",
  "School of Chemistry and Biology in Shymkent",
  "School of Physics and Mathematics in Shymkent",
  "School of Physics and Mathematics in Taraz",
  "School of Chemistry and Biology in Kyzylorda",
  "School of Chemistry and Biology in Pavlodar",
  "School of Chemistry and Biology in Atyrau",
  "School of Physics and Mathematics in Almaty",
  "School of Physics and Mathematics in Kostanay",
  "School of Chemistry and Biology in Petropavlovsk",
  "School of Chemistry and Biology in Almaty",
  "chool of Chemistry and Biology in Aktau",
  "International School of Nur-Sultan",
  "School of Chemistry and Biology in Turkestan",
];

export const listOfMajors = [
  "IT",
  "Business",
  "Journalism",
  "Engineering",
  "Logistics",
  "Marketing",
  "The medicine",
  "Management",
  "Teachers",
  "Project management",
  "Finance",
  "Economy",
  "Jurisprudence",
];

export const listOfCountries = [
  "Ascension Island",
  "Andorra",
  "United Arab Emirates",
  "Afghanistan",
  "Antigua & Barbuda",
  "Anguilla",
  "Albania",
  "Armenia",
  "Angola",
  "Antarctica",
  "Argentina",
  "American Samoa",
  "Austria",
  "Australia",
  "Aruba",
  "Åland Islands",
  "Azerbaijan",
  "Bosnia & Herzegovina",
  "Barbados",
  "Bangladesh",
  "Belgium",
  "Burkina Faso",
  "Bulgaria",
  "Bahrain",
  "Burundi",
  "Benin",
  "St Barthélemy",
  "Bermuda",
  "Brunei",
  "Bolivia",
  "Caribbean Netherlands",
  "Brazil",
  "Bahamas",
  "Bhutan",
  "Bouvet Island",
  "Botswana",
  "Belarus",
  "Belize",
  "Canada",
  "Cocos [Keeling] Islands",
  "Congo - Kinshasa",
  "Central African Republic",
  "Congo - Brazzaville",
  "Switzerland",
  "Côte d’Ivoire",
  "Cook Islands",
  "Chile",
  "Cameroon",
  "China mainland",
  "Colombia",
  "Clipperton Island",
  "Costa Rica",
  "Cuba",
  "Cape Verde",
  "Curaçao",
  "Christmas Island",
  "Cyprus",
  "Czechia",
  "Germany",
  "Diego Garcia",
  "Djibouti",
  "Denmark",
  "Dominica",
  "Dominican Republic",
  "Algeria",
  "Ceuta & Melilla",
  "Ecuador",
  "Estonia",
  "Egypt",
  "Western Sahara",
  "Eritrea",
  "Spain",
  "Ethiopia",
  "Finland",
  "Fiji",
  "Falkland Islands",
  "Micronesia",
  "Faroe Islands",
  "France",
  "Gabon",
  "United Kingdom",
  "Grenada",
  "Georgia",
  "French Guiana",
  "Guernsey",
  "Ghana",
  "Gibraltar",
  "Greenland",
  "Gambia",
  "Guinea",
  "Guadeloupe",
  "Equatorial Guinea",
  "Greece",
  "So. Georgia & So. Sandwich Isl.",
  "Guatemala",
  "Guam",
  "Guinea-Bissau",
  "Guyana",
  "Hong Kong",
  "Heard & McDonald Islands",
  "Honduras",
  "Croatia",
  "Haiti",
  "Hungary",
  "Canary Islands",
  "Indonesia",
  "Ireland",
  "Israel",
  "Isle of Man",
  "India",
  "Chagos Archipelago",
  "Iraq",
  "Iran",
  "Iceland",
  "Italy",
  "Jersey",
  "Jamaica",
  "Jordan",
  "Japan",
  "Kenya",
  "Kyrgyzstan",
  "Cambodia",
  "Kiribati",
  "Comoros",
  "St Kitts & Nevis",
  "North Korea",
  "South Korea",
  "Kuwait",
  "Cayman Islands",
  "Kazakhstan",
  "Laos",
  "Lebanon",
  "St Lucia",
  "Liechtenstein",
  "Sri Lanka",
  "Liberia",
  "Lesotho",
  "Lithuania",
  "Luxembourg",
  "Latvia",
  "Libya",
  "Morocco",
  "Monaco",
  "Moldova",
  "Montenegro",
  "St Martin",
  "Madagascar",
  "Marshall Islands",
  "North Macedonia",
  "Mali",
  "Myanmar [Burma]",
  "Mongolia",
  "Macao",
  "Northern Mariana Islands",
  "Martinique",
  "Mauritania",
  "Montserrat",
  "Malta",
  "Mauritius",
  "Maldives",
  "Malawi",
  "Mexico",
  "Malaysia",
  "Mozambique",
  "Namibia",
  "New Caledonia",
  "Niger",
  "Norfolk Island",
  "Nigeria",
  "Nicaragua",
  "Netherlands",
  "Norway",
  "Nepal",
  "Nauru",
  "Niue",
  "New Zealand",
  "Oman",
  "Panama",
  "Peru",
  "French Polynesia",
  "Papua New Guinea",
  "Philippines",
  "Pakistan",
  "Poland",
  "St Pierre & Miquelon",
  "Pitcairn Islands",
  "Puerto Rico",
  "Palestinian Territories",
  "Portugal",
  "Palau",
  "Paraguay",
  "Qatar",
  "Réunion",
  "Romania",
  "Serbia",
  "Russia",
  "Rwanda",
  "Saudi Arabia",
  "Solomon Islands",
  "Seychelles",
  "Sudan",
  "Sweden",
  "Singapore",
  "St Helena",
  "Slovenia",
  "Svalbard & Jan Mayen",
  "Slovakia",
  "Sierra Leone",
  "San Marino",
  "Senegal",
  "Somalia",
  "Suriname",
  "South Sudan",
  "São Tomé & Príncipe",
  "El Salvador",
  "Sint Maarten",
  "Syria",
  "Eswatini",
  "Tristan da Cunha",
  "Turks & Caicos Islands",
  "Chad",
  "French Southern Territories",
  "Togo",
  "Thailand",
  "Tajikistan",
  "Tokelau",
  "Timor-Leste",
  "Turkmenistan",
  "Tunisia",
  "Tonga",
  "Turkey",
  "Trinidad & Tobago",
  "Tuvalu",
  "Taiwan",
  "Tanzania",
  "Ukraine",
  "Uganda",
  "US Outlying Islands",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vatican City",
  "St Vincent & the Grenadines",
  "Venezuela",
  "British Virgin Islands",
  "US Virgin Islands",
  "Vietnam",
  "Vanuatu",
  "Wallis & Futuna",
  "Samoa",
  "Kosovo",
  "Yemen",
  "Mayotte",
  "South Africa",
  "Zambia",
  "Zimbabwe",
].sort();
